name: Apply migrations

on:
  push:
    branches:
      - master

env:
  TAG: blog-migrator
  SERVICE_NAME: blog-migrator
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_HOST: ${{ secrets.DB_HOST }}


jobs:
  apply-migrations:
    name: Apply migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          docker build -t $TAG migrator/

      - name: Run migrator
        run: |
          docker run \
            --name "$SERVICE_NAME" \
            --env DB_USER="$DB_USER" \
            --env DB_PASSWORD="$DB_PASSWORD" \
            --env DB_NAME="$DB_NAME" \
            --env DB_HOST="$DB_HOST" \
            "$TAG"
