name: Apply migrations

on:
  push:
    branches:
      - master

env:
  TAG: blog-migrator
  SERVICE_NAME: blog-migrator
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  GCP_DB_INSTANCE: ${{ secrets.GCP_DB_INSTANCE }}
  GCP_RUN_SA_KEY: ${{ secrets.GCP_RUN_SA_KEY }}


jobs:
  apply-migrations:
    name: Apply migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          docker build -t $TAG migrator/

      - name: Run migrator
        run: |
          wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy -q & \
          chmod +x cloud_sql_proxy & \
          ./cloud_sql_proxy -dir=/cloudsql -instances="$GCP_DB_INSTANCE" -token="$GCP_RUN_SA_KEY" & \
          docker run \
            --name "$SERVICE_NAME" \
            --env DB_USER="$DB_USER" \
            --env DB_PASSWORD="$DB_PASSWORD" \
            --env DB_NAME="$DB_NAME" \
            --env DB_HOST="/cloudsql/$GCP_DB_INSTANCE" \
            "$TAG"
